CREATE TABLE user (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  profile_pic VARCHAR(255) NOT NULL
);

CREATE TABLE dietprefs (
  id VARCHAR(255) PRIMARY KEY,
  base_pref VARCHAR(255) NOT NULL
);